server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/your_database
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  flyway:
    schemas: authentication, financial, log
    baseline-on-migrate: true

  jpa:
    show-sql: true

  rabbitmq:
    host: rabbitmq
    username: admin
    password: admin
