server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/your_database
    username: test
    password: test
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    host: rabbitmq
    username: admin
    password: admin
